language: python
python: "2.7"
services:
  - redis-server
  - mysql
  - postgresql
env:
  - TOXENV=py27
install:
  - pip install tox coveralls
before_script:
  - mysql -e 'create database test;'
script: tox
after_success:
  if [ "$TOXENV" == "py27" ]; then coveralls; fi
